version: '3.8'

services:
  postgres_db:
    container_name: appsmarket_postgres_db
    image: postgres:13-bullseye
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: appsmarket_DRF
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - ./.env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.development
      PYTHONPATH: /app
      PYTHONUNBUFFERED: '1'
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db

  


  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
      - ./frontend/node_modules:/app/node_modules
    stdin_open: true
    tty: true



  

volumes:
  postgres_data:

